# Generated by Django 2.2.28 on 2024-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0004_auto_20240307_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
