# Generated by Django 2.2.28 on 2024-03-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0007_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
