# Generated by Django 2.2.28 on 2024-03-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0008_auto_20240308_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
