# Generated by Django 2.2.28 on 2024-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0009_page_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Book',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
