# Generated by Django 2.2.28 on 2024-03-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0010_auto_20240308_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='book',
            name='estimatedreadingtime',
            field=models.TimeField(null=True),
        ),
    ]
