# Generated by Django 2.2.28 on 2024-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0011_auto_20240308_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='estimatedreadingtime',
            field=models.TextField(null=True),
        ),
    ]
