# Generated by Django 2.2.28 on 2024-03-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0014_remove_book_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.URLField(default=''),
        ),
    ]
