# Generated by Django 2.2.28 on 2024-03-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0016_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='profilepicture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
