# Generated by Django 2.2.28 on 2024-03-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0017_auto_20240308_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.URLField(),
        ),
    ]
