# Generated by Django 2.2.28 on 2024-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0019_auto_20240308_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
