# Generated by Django 2.2.28 on 2024-03-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0021_auto_20240312_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
