# Generated by Django 2.2.28 on 2024-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0022_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_categories',
            field=models.ManyToManyField(to='realm.Category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_favourites',
            field=models.BooleanField(default=False),
        ),
    ]
