# Generated by Django 2.2.28 on 2024-03-17 23:41

from django.db import migrations, models
import realm.models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0025_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_end_date',
            field=models.DateTimeField(default=realm.models.default_rental_end_date),
        ),
    ]
