# Generated by Django 2.2.28 on 2024-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0029_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
