# Generated by Django 2.2.28 on 2024-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0031_auto_20240322_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcover',
            field=models.ImageField(blank=True, upload_to='../static'),
        ),
    ]
