# Generated by Django 2.2.28 on 2024-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0032_book_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookcover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
